CREATE TABLE Airplane (
                          id int generated by default as identity primary key ,
                          name varchar(255)
);
CREATE TABLE Temperature (
                             id int generated by default as identity primary key ,
                             received_at TIMESTAMP,
                             value double precision,
                             airplane_id int references Airplane(id) on delete cascade
);
CREATE TABLE Pressure (
                          id int generated by default as identity primary key ,
                          received_at TIMESTAMP,
                          value double precision,
                          airplane_id int references Airplane(id) on delete cascade
);


