CREATE TABLE microcontroller (
                                 id int generated by default as identity primary key ,
                                 name VARCHAR(255),
                                 registered_at TIMESTAMP
);

CREATE TABLE pressure (
                          id int generated by default as identity primary key ,
                          received_at TIMESTAMP,
                          value double precision
);

CREATE TABLE temperature (
                             id int generated by default as identity primary key ,
                             received_at TIMESTAMP,
                             value double precision
);
