create table Sensor(
    id int generated by default as identity primary key ,
    name varchar unique,
    registered_at timestamp
);

create table Measurement(
    id int generated by default as identity primary key ,
    value float ,
    raining boolean ,
    sensor_id int references Sensor(id) on delete cascade not null ,
    added_at timestamp
);